# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_vrpn_Button', [dirname(__file__)])
        except ImportError:
            import _vrpn_Button
            return _vrpn_Button
        if fp is not None:
            try:
                _mod = imp.load_module('_vrpn_Button', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _vrpn_Button = swig_import_helper()
    del swig_import_helper
else:
    import _vrpn_Button
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


vrpn_DEFAULT_LISTEN_PORT_NO = _vrpn_Button.vrpn_DEFAULT_LISTEN_PORT_NO
VRPN_VIEWPOINT_H = _vrpn_Button.VRPN_VIEWPOINT_H
VRPN_SYSTEMDRIVE = _vrpn_Button.VRPN_SYSTEMDRIVE
VRPN_PHASESPACE_LIB_PATH = _vrpn_Button.VRPN_PHASESPACE_LIB_PATH
VRPN_WIIUSE_H = _vrpn_Button.VRPN_WIIUSE_H
VRPN_TRIVISIOCOLIBRI_H = _vrpn_Button.VRPN_TRIVISIOCOLIBRI_H
VRPN_TRIVISIOCOLIBRI_LIB_PATH = _vrpn_Button.VRPN_TRIVISIOCOLIBRI_LIB_PATH
VRPN_GHOST_31_PATH = _vrpn_Button.VRPN_GHOST_31_PATH
VRPN_GHOST_40_PATH = _vrpn_Button.VRPN_GHOST_40_PATH
VRPN_NIDAQ_PATH = _vrpn_Button.VRPN_NIDAQ_PATH
VRPN_USDIGITAL_PATH = _vrpn_Button.VRPN_USDIGITAL_PATH
vrpn_TEXT_NORMAL = _vrpn_Button.vrpn_TEXT_NORMAL
vrpn_TEXT_WARNING = _vrpn_Button.vrpn_TEXT_WARNING
vrpn_TEXT_ERROR = _vrpn_Button.vrpn_TEXT_ERROR
class vrpn_TextPrinter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_TextPrinter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_TextPrinter, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _vrpn_Button.new_vrpn_TextPrinter()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpn_TextPrinter
    __del__ = lambda self : None;
    def add_object(self, *args): return _vrpn_Button.vrpn_TextPrinter_add_object(self, *args)
    def remove_object(self, *args): return _vrpn_Button.vrpn_TextPrinter_remove_object(self, *args)
    def set_min_level_to_print(self, *args): return _vrpn_Button.vrpn_TextPrinter_set_min_level_to_print(self, *args)
    def set_ostream_to_use(self, *args): return _vrpn_Button.vrpn_TextPrinter_set_ostream_to_use(self, *args)
vrpn_TextPrinter_swigregister = _vrpn_Button.vrpn_TextPrinter_swigregister
vrpn_TextPrinter_swigregister(vrpn_TextPrinter)
cvar = _vrpn_Button.cvar
vrpn_MAX_BCADRS = cvar.vrpn_MAX_BCADRS
vrpn_MAX_TEXT_LEN = cvar.vrpn_MAX_TEXT_LEN

class vrpn_BaseClassUnique(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_BaseClassUnique, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_BaseClassUnique, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _vrpn_Button.new_vrpn_BaseClassUnique()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpn_BaseClassUnique
    __del__ = lambda self : None;
    def connectionPtr(self): return _vrpn_Button.vrpn_BaseClassUnique_connectionPtr(self)
    __swig_setmethods__["shutup"] = _vrpn_Button.vrpn_BaseClassUnique_shutup_set
    __swig_getmethods__["shutup"] = _vrpn_Button.vrpn_BaseClassUnique_shutup_get
    if _newclass:shutup = _swig_property(_vrpn_Button.vrpn_BaseClassUnique_shutup_get, _vrpn_Button.vrpn_BaseClassUnique_shutup_set)
vrpn_BaseClassUnique_swigregister = _vrpn_Button.vrpn_BaseClassUnique_swigregister
vrpn_BaseClassUnique_swigregister(vrpn_BaseClassUnique)

class vrpn_BaseClass(vrpn_BaseClassUnique):
    __swig_setmethods__ = {}
    for _s in [vrpn_BaseClassUnique]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_BaseClass, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_BaseClassUnique]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_BaseClass, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Button.delete_vrpn_BaseClass
    __del__ = lambda self : None;
    def mainloop(self): return _vrpn_Button.vrpn_BaseClass_mainloop(self)
vrpn_BaseClass_swigregister = _vrpn_Button.vrpn_BaseClass_swigregister
vrpn_BaseClass_swigregister(vrpn_BaseClass)

LISTEN = _vrpn_Button.LISTEN
CONNECTED = _vrpn_Button.CONNECTED
COOKIE_PENDING = _vrpn_Button.COOKIE_PENDING
TRYING_TO_CONNECT = _vrpn_Button.TRYING_TO_CONNECT
BROKEN = _vrpn_Button.BROKEN
LOGGING = _vrpn_Button.LOGGING
class vrpn_HANDLERPARAM(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_HANDLERPARAM, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_HANDLERPARAM, name)
    __repr__ = _swig_repr
    __swig_setmethods__["type"] = _vrpn_Button.vrpn_HANDLERPARAM_type_set
    __swig_getmethods__["type"] = _vrpn_Button.vrpn_HANDLERPARAM_type_get
    if _newclass:type = _swig_property(_vrpn_Button.vrpn_HANDLERPARAM_type_get, _vrpn_Button.vrpn_HANDLERPARAM_type_set)
    __swig_setmethods__["sender"] = _vrpn_Button.vrpn_HANDLERPARAM_sender_set
    __swig_getmethods__["sender"] = _vrpn_Button.vrpn_HANDLERPARAM_sender_get
    if _newclass:sender = _swig_property(_vrpn_Button.vrpn_HANDLERPARAM_sender_get, _vrpn_Button.vrpn_HANDLERPARAM_sender_set)
    __swig_setmethods__["msg_time"] = _vrpn_Button.vrpn_HANDLERPARAM_msg_time_set
    __swig_getmethods__["msg_time"] = _vrpn_Button.vrpn_HANDLERPARAM_msg_time_get
    if _newclass:msg_time = _swig_property(_vrpn_Button.vrpn_HANDLERPARAM_msg_time_get, _vrpn_Button.vrpn_HANDLERPARAM_msg_time_set)
    __swig_setmethods__["payload_len"] = _vrpn_Button.vrpn_HANDLERPARAM_payload_len_set
    __swig_getmethods__["payload_len"] = _vrpn_Button.vrpn_HANDLERPARAM_payload_len_get
    if _newclass:payload_len = _swig_property(_vrpn_Button.vrpn_HANDLERPARAM_payload_len_get, _vrpn_Button.vrpn_HANDLERPARAM_payload_len_set)
    __swig_setmethods__["buffer"] = _vrpn_Button.vrpn_HANDLERPARAM_buffer_set
    __swig_getmethods__["buffer"] = _vrpn_Button.vrpn_HANDLERPARAM_buffer_get
    if _newclass:buffer = _swig_property(_vrpn_Button.vrpn_HANDLERPARAM_buffer_get, _vrpn_Button.vrpn_HANDLERPARAM_buffer_set)
    def __init__(self): 
        this = _vrpn_Button.new_vrpn_HANDLERPARAM()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpn_HANDLERPARAM
    __del__ = lambda self : None;
vrpn_HANDLERPARAM_swigregister = _vrpn_Button.vrpn_HANDLERPARAM_swigregister
vrpn_HANDLERPARAM_swigregister(vrpn_HANDLERPARAM)

class vrpn_LOGLIST(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_LOGLIST, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_LOGLIST, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _vrpn_Button.vrpn_LOGLIST_data_set
    __swig_getmethods__["data"] = _vrpn_Button.vrpn_LOGLIST_data_get
    if _newclass:data = _swig_property(_vrpn_Button.vrpn_LOGLIST_data_get, _vrpn_Button.vrpn_LOGLIST_data_set)
    __swig_setmethods__["next"] = _vrpn_Button.vrpn_LOGLIST_next_set
    __swig_getmethods__["next"] = _vrpn_Button.vrpn_LOGLIST_next_get
    if _newclass:next = _swig_property(_vrpn_Button.vrpn_LOGLIST_next_get, _vrpn_Button.vrpn_LOGLIST_next_set)
    __swig_setmethods__["prev"] = _vrpn_Button.vrpn_LOGLIST_prev_set
    __swig_getmethods__["prev"] = _vrpn_Button.vrpn_LOGLIST_prev_get
    if _newclass:prev = _swig_property(_vrpn_Button.vrpn_LOGLIST_prev_get, _vrpn_Button.vrpn_LOGLIST_prev_set)
    def __init__(self): 
        this = _vrpn_Button.new_vrpn_LOGLIST()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpn_LOGLIST
    __del__ = lambda self : None;
vrpn_LOGLIST_swigregister = _vrpn_Button.vrpn_LOGLIST_swigregister
vrpn_LOGLIST_swigregister(vrpn_LOGLIST)
vrpn_ALIGN = cvar.vrpn_ALIGN
vrpn_CONNECTION_MAX_SENDERS = cvar.vrpn_CONNECTION_MAX_SENDERS
vrpn_CONNECTION_MAX_TYPES = cvar.vrpn_CONNECTION_MAX_TYPES
vrpn_ANY_SENDER = cvar.vrpn_ANY_SENDER
vrpn_ANY_TYPE = cvar.vrpn_ANY_TYPE
vrpn_CONNECTION_TCP_BUFLEN = cvar.vrpn_CONNECTION_TCP_BUFLEN
vrpn_CONNECTION_UDP_BUFLEN = cvar.vrpn_CONNECTION_UDP_BUFLEN
vrpn_MAX_ENDPOINTS = cvar.vrpn_MAX_ENDPOINTS
vrpn_CONNECTION_SENDER_DESCRIPTION = cvar.vrpn_CONNECTION_SENDER_DESCRIPTION
vrpn_CONNECTION_TYPE_DESCRIPTION = cvar.vrpn_CONNECTION_TYPE_DESCRIPTION
vrpn_CONNECTION_UDP_DESCRIPTION = cvar.vrpn_CONNECTION_UDP_DESCRIPTION
vrpn_CONNECTION_LOG_DESCRIPTION = cvar.vrpn_CONNECTION_LOG_DESCRIPTION
vrpn_CONNECTION_DISCONNECT_MESSAGE = cvar.vrpn_CONNECTION_DISCONNECT_MESSAGE
vrpn_CONNECTION_RELIABLE = cvar.vrpn_CONNECTION_RELIABLE
vrpn_CONNECTION_FIXED_LATENCY = cvar.vrpn_CONNECTION_FIXED_LATENCY
vrpn_CONNECTION_LOW_LATENCY = cvar.vrpn_CONNECTION_LOW_LATENCY
vrpn_CONNECTION_FIXED_THROUGHPUT = cvar.vrpn_CONNECTION_FIXED_THROUGHPUT
vrpn_CONNECTION_HIGH_THROUGHPUT = cvar.vrpn_CONNECTION_HIGH_THROUGHPUT
vrpn_LOG_NONE = cvar.vrpn_LOG_NONE
vrpn_LOG_INCOMING = cvar.vrpn_LOG_INCOMING
vrpn_LOG_OUTGOING = cvar.vrpn_LOG_OUTGOING

class BoundEndpointAllocator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BoundEndpointAllocator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BoundEndpointAllocator, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _vrpn_Button.new_BoundEndpointAllocator(*args)
        try: self.this.append(this)
        except: self.this = this
    def __call__(self, *args): return _vrpn_Button.BoundEndpointAllocator___call__(self, *args)
    __swig_destroy__ = _vrpn_Button.delete_BoundEndpointAllocator
    __del__ = lambda self : None;
BoundEndpointAllocator_swigregister = _vrpn_Button.BoundEndpointAllocator_swigregister
BoundEndpointAllocator_swigregister(BoundEndpointAllocator)

class vrpnMsgCallbackEntry(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpnMsgCallbackEntry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpnMsgCallbackEntry, name)
    __repr__ = _swig_repr
    __swig_setmethods__["handler"] = _vrpn_Button.vrpnMsgCallbackEntry_handler_set
    __swig_getmethods__["handler"] = _vrpn_Button.vrpnMsgCallbackEntry_handler_get
    if _newclass:handler = _swig_property(_vrpn_Button.vrpnMsgCallbackEntry_handler_get, _vrpn_Button.vrpnMsgCallbackEntry_handler_set)
    __swig_setmethods__["userdata"] = _vrpn_Button.vrpnMsgCallbackEntry_userdata_set
    __swig_getmethods__["userdata"] = _vrpn_Button.vrpnMsgCallbackEntry_userdata_get
    if _newclass:userdata = _swig_property(_vrpn_Button.vrpnMsgCallbackEntry_userdata_get, _vrpn_Button.vrpnMsgCallbackEntry_userdata_set)
    __swig_setmethods__["sender"] = _vrpn_Button.vrpnMsgCallbackEntry_sender_set
    __swig_getmethods__["sender"] = _vrpn_Button.vrpnMsgCallbackEntry_sender_get
    if _newclass:sender = _swig_property(_vrpn_Button.vrpnMsgCallbackEntry_sender_get, _vrpn_Button.vrpnMsgCallbackEntry_sender_set)
    __swig_setmethods__["next"] = _vrpn_Button.vrpnMsgCallbackEntry_next_set
    __swig_getmethods__["next"] = _vrpn_Button.vrpnMsgCallbackEntry_next_get
    if _newclass:next = _swig_property(_vrpn_Button.vrpnMsgCallbackEntry_next_get, _vrpn_Button.vrpnMsgCallbackEntry_next_set)
    def __init__(self): 
        this = _vrpn_Button.new_vrpnMsgCallbackEntry()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpnMsgCallbackEntry
    __del__ = lambda self : None;
vrpnMsgCallbackEntry_swigregister = _vrpn_Button.vrpnMsgCallbackEntry_swigregister
vrpnMsgCallbackEntry_swigregister(vrpnMsgCallbackEntry)

class vrpnLogFilterEntry(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpnLogFilterEntry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpnLogFilterEntry, name)
    __repr__ = _swig_repr
    __swig_setmethods__["filter"] = _vrpn_Button.vrpnLogFilterEntry_filter_set
    __swig_getmethods__["filter"] = _vrpn_Button.vrpnLogFilterEntry_filter_get
    if _newclass:filter = _swig_property(_vrpn_Button.vrpnLogFilterEntry_filter_get, _vrpn_Button.vrpnLogFilterEntry_filter_set)
    __swig_setmethods__["userdata"] = _vrpn_Button.vrpnLogFilterEntry_userdata_set
    __swig_getmethods__["userdata"] = _vrpn_Button.vrpnLogFilterEntry_userdata_get
    if _newclass:userdata = _swig_property(_vrpn_Button.vrpnLogFilterEntry_userdata_get, _vrpn_Button.vrpnLogFilterEntry_userdata_set)
    __swig_setmethods__["next"] = _vrpn_Button.vrpnLogFilterEntry_next_set
    __swig_getmethods__["next"] = _vrpn_Button.vrpnLogFilterEntry_next_get
    if _newclass:next = _swig_property(_vrpn_Button.vrpnLogFilterEntry_next_get, _vrpn_Button.vrpnLogFilterEntry_next_set)
    def __init__(self): 
        this = _vrpn_Button.new_vrpnLogFilterEntry()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpnLogFilterEntry
    __del__ = lambda self : None;
vrpnLogFilterEntry_swigregister = _vrpn_Button.vrpnLogFilterEntry_swigregister
vrpnLogFilterEntry_swigregister(vrpnLogFilterEntry)

class vrpn_Endpoint(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Endpoint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Endpoint, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Button.delete_vrpn_Endpoint
    __del__ = lambda self : None;
    def local_type_id(self, *args): return _vrpn_Button.vrpn_Endpoint_local_type_id(self, *args)
    def local_sender_id(self, *args): return _vrpn_Button.vrpn_Endpoint_local_sender_id(self, *args)
    def doing_okay(self): return _vrpn_Button.vrpn_Endpoint_doing_okay(self)
    def init(self): return _vrpn_Button.vrpn_Endpoint_init(self)
    def mainloop(self, *args): return _vrpn_Button.vrpn_Endpoint_mainloop(self, *args)
    def clear_other_senders_and_types(self): return _vrpn_Button.vrpn_Endpoint_clear_other_senders_and_types(self)
    def newLocalSender(self, *args): return _vrpn_Button.vrpn_Endpoint_newLocalSender(self, *args)
    def newLocalType(self, *args): return _vrpn_Button.vrpn_Endpoint_newLocalType(self, *args)
    def newRemoteType(self, *args): return _vrpn_Button.vrpn_Endpoint_newRemoteType(self, *args)
    def newRemoteSender(self, *args): return _vrpn_Button.vrpn_Endpoint_newRemoteSender(self, *args)
    def pack_message(self, *args): return _vrpn_Button.vrpn_Endpoint_pack_message(self, *args)
    def send_pending_reports(self): return _vrpn_Button.vrpn_Endpoint_send_pending_reports(self)
    def pack_log_description(self): return _vrpn_Button.vrpn_Endpoint_pack_log_description(self)
    def setup_new_connection(self): return _vrpn_Button.vrpn_Endpoint_setup_new_connection(self)
    def poll_for_cookie(self, timeout = None): return _vrpn_Button.vrpn_Endpoint_poll_for_cookie(self, timeout)
    def finish_new_connection_setup(self): return _vrpn_Button.vrpn_Endpoint_finish_new_connection_setup(self)
    def drop_connection(self): return _vrpn_Button.vrpn_Endpoint_drop_connection(self)
    def clearBuffers(self): return _vrpn_Button.vrpn_Endpoint_clearBuffers(self)
    def pack_sender_description(self, *args): return _vrpn_Button.vrpn_Endpoint_pack_sender_description(self, *args)
    def pack_type_description(self, *args): return _vrpn_Button.vrpn_Endpoint_pack_type_description(self, *args)
    __swig_setmethods__["status"] = _vrpn_Button.vrpn_Endpoint_status_set
    __swig_getmethods__["status"] = _vrpn_Button.vrpn_Endpoint_status_get
    if _newclass:status = _swig_property(_vrpn_Button.vrpn_Endpoint_status_get, _vrpn_Button.vrpn_Endpoint_status_set)
    __swig_setmethods__["d_remoteLogMode"] = _vrpn_Button.vrpn_Endpoint_d_remoteLogMode_set
    __swig_getmethods__["d_remoteLogMode"] = _vrpn_Button.vrpn_Endpoint_d_remoteLogMode_get
    if _newclass:d_remoteLogMode = _swig_property(_vrpn_Button.vrpn_Endpoint_d_remoteLogMode_get, _vrpn_Button.vrpn_Endpoint_d_remoteLogMode_set)
    __swig_setmethods__["d_remoteInLogName"] = _vrpn_Button.vrpn_Endpoint_d_remoteInLogName_set
    __swig_getmethods__["d_remoteInLogName"] = _vrpn_Button.vrpn_Endpoint_d_remoteInLogName_get
    if _newclass:d_remoteInLogName = _swig_property(_vrpn_Button.vrpn_Endpoint_d_remoteInLogName_get, _vrpn_Button.vrpn_Endpoint_d_remoteInLogName_set)
    __swig_setmethods__["d_remoteOutLogName"] = _vrpn_Button.vrpn_Endpoint_d_remoteOutLogName_set
    __swig_getmethods__["d_remoteOutLogName"] = _vrpn_Button.vrpn_Endpoint_d_remoteOutLogName_get
    if _newclass:d_remoteOutLogName = _swig_property(_vrpn_Button.vrpn_Endpoint_d_remoteOutLogName_get, _vrpn_Button.vrpn_Endpoint_d_remoteOutLogName_set)
    __swig_setmethods__["rhostname"] = _vrpn_Button.vrpn_Endpoint_rhostname_set
    __swig_getmethods__["rhostname"] = _vrpn_Button.vrpn_Endpoint_rhostname_get
    if _newclass:rhostname = _swig_property(_vrpn_Button.vrpn_Endpoint_rhostname_get, _vrpn_Button.vrpn_Endpoint_rhostname_set)
    __swig_setmethods__["d_inLog"] = _vrpn_Button.vrpn_Endpoint_d_inLog_set
    __swig_getmethods__["d_inLog"] = _vrpn_Button.vrpn_Endpoint_d_inLog_get
    if _newclass:d_inLog = _swig_property(_vrpn_Button.vrpn_Endpoint_d_inLog_get, _vrpn_Button.vrpn_Endpoint_d_inLog_set)
    __swig_setmethods__["d_outLog"] = _vrpn_Button.vrpn_Endpoint_d_outLog_set
    __swig_getmethods__["d_outLog"] = _vrpn_Button.vrpn_Endpoint_d_outLog_get
    if _newclass:d_outLog = _swig_property(_vrpn_Button.vrpn_Endpoint_d_outLog_get, _vrpn_Button.vrpn_Endpoint_d_outLog_set)
    def setLogNames(self, *args): return _vrpn_Button.vrpn_Endpoint_setLogNames(self, *args)
    def openLogs(self): return _vrpn_Button.vrpn_Endpoint_openLogs(self)
    __swig_getmethods__["handle_sender_message"] = lambda x: _vrpn_Button.vrpn_Endpoint_handle_sender_message
    if _newclass:handle_sender_message = staticmethod(_vrpn_Button.vrpn_Endpoint_handle_sender_message)
    __swig_getmethods__["handle_type_message"] = lambda x: _vrpn_Button.vrpn_Endpoint_handle_type_message
    if _newclass:handle_type_message = staticmethod(_vrpn_Button.vrpn_Endpoint_handle_type_message)
    def setConnection(self, *args): return _vrpn_Button.vrpn_Endpoint_setConnection(self, *args)
    def getConnection(self): return _vrpn_Button.vrpn_Endpoint_getConnection(self)
vrpn_Endpoint_swigregister = _vrpn_Button.vrpn_Endpoint_swigregister
vrpn_Endpoint_swigregister(vrpn_Endpoint)

def vrpn_Endpoint_handle_sender_message(*args):
  return _vrpn_Button.vrpn_Endpoint_handle_sender_message(*args)
vrpn_Endpoint_handle_sender_message = _vrpn_Button.vrpn_Endpoint_handle_sender_message

def vrpn_Endpoint_handle_type_message(*args):
  return _vrpn_Button.vrpn_Endpoint_handle_type_message(*args)
vrpn_Endpoint_handle_type_message = _vrpn_Button.vrpn_Endpoint_handle_type_message

class vrpn_Endpoint_IP(vrpn_Endpoint):
    __swig_setmethods__ = {}
    for _s in [vrpn_Endpoint]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Endpoint_IP, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Endpoint]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Endpoint_IP, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _vrpn_Button.new_vrpn_Endpoint_IP(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpn_Endpoint_IP
    __del__ = lambda self : None;
    def doing_okay(self): return _vrpn_Button.vrpn_Endpoint_IP_doing_okay(self)
    def outbound_udp_open(self): return _vrpn_Button.vrpn_Endpoint_IP_outbound_udp_open(self)
    def tcp_outbuf_size(self): return _vrpn_Button.vrpn_Endpoint_IP_tcp_outbuf_size(self)
    def udp_outbuf_size(self): return _vrpn_Button.vrpn_Endpoint_IP_udp_outbuf_size(self)
    def init(self): return _vrpn_Button.vrpn_Endpoint_IP_init(self)
    def mainloop(self, *args): return _vrpn_Button.vrpn_Endpoint_IP_mainloop(self, *args)
    def pack_message(self, *args): return _vrpn_Button.vrpn_Endpoint_IP_pack_message(self, *args)
    def send_pending_reports(self): return _vrpn_Button.vrpn_Endpoint_IP_send_pending_reports(self)
    def pack_udp_description(self, *args): return _vrpn_Button.vrpn_Endpoint_IP_pack_udp_description(self, *args)
    def handle_tcp_messages(self, *args): return _vrpn_Button.vrpn_Endpoint_IP_handle_tcp_messages(self, *args)
    def handle_udp_messages(self, *args): return _vrpn_Button.vrpn_Endpoint_IP_handle_udp_messages(self, *args)
    def connect_tcp_to(self, *args): return _vrpn_Button.vrpn_Endpoint_IP_connect_tcp_to(self, *args)
    def connect_udp_to(self, *args): return _vrpn_Button.vrpn_Endpoint_IP_connect_udp_to(self, *args)
    def set_tcp_outbuf_size(self, *args): return _vrpn_Button.vrpn_Endpoint_IP_set_tcp_outbuf_size(self, *args)
    def setup_new_connection(self): return _vrpn_Button.vrpn_Endpoint_IP_setup_new_connection(self)
    def poll_for_cookie(self, timeout = None): return _vrpn_Button.vrpn_Endpoint_IP_poll_for_cookie(self, timeout)
    def finish_new_connection_setup(self): return _vrpn_Button.vrpn_Endpoint_IP_finish_new_connection_setup(self)
    def drop_connection(self): return _vrpn_Button.vrpn_Endpoint_IP_drop_connection(self)
    def clearBuffers(self): return _vrpn_Button.vrpn_Endpoint_IP_clearBuffers(self)
    def setNICaddress(self, *args): return _vrpn_Button.vrpn_Endpoint_IP_setNICaddress(self, *args)
    __swig_setmethods__["d_tcpSocket"] = _vrpn_Button.vrpn_Endpoint_IP_d_tcpSocket_set
    __swig_getmethods__["d_tcpSocket"] = _vrpn_Button.vrpn_Endpoint_IP_d_tcpSocket_get
    if _newclass:d_tcpSocket = _swig_property(_vrpn_Button.vrpn_Endpoint_IP_d_tcpSocket_get, _vrpn_Button.vrpn_Endpoint_IP_d_tcpSocket_set)
    __swig_setmethods__["d_tcpListenSocket"] = _vrpn_Button.vrpn_Endpoint_IP_d_tcpListenSocket_set
    __swig_getmethods__["d_tcpListenSocket"] = _vrpn_Button.vrpn_Endpoint_IP_d_tcpListenSocket_get
    if _newclass:d_tcpListenSocket = _swig_property(_vrpn_Button.vrpn_Endpoint_IP_d_tcpListenSocket_get, _vrpn_Button.vrpn_Endpoint_IP_d_tcpListenSocket_set)
    __swig_setmethods__["d_tcpListenPort"] = _vrpn_Button.vrpn_Endpoint_IP_d_tcpListenPort_set
    __swig_getmethods__["d_tcpListenPort"] = _vrpn_Button.vrpn_Endpoint_IP_d_tcpListenPort_get
    if _newclass:d_tcpListenPort = _swig_property(_vrpn_Button.vrpn_Endpoint_IP_d_tcpListenPort_get, _vrpn_Button.vrpn_Endpoint_IP_d_tcpListenPort_set)
    __swig_setmethods__["d_udpLobSocket"] = _vrpn_Button.vrpn_Endpoint_IP_d_udpLobSocket_set
    __swig_getmethods__["d_udpLobSocket"] = _vrpn_Button.vrpn_Endpoint_IP_d_udpLobSocket_get
    if _newclass:d_udpLobSocket = _swig_property(_vrpn_Button.vrpn_Endpoint_IP_d_udpLobSocket_get, _vrpn_Button.vrpn_Endpoint_IP_d_udpLobSocket_set)
    __swig_setmethods__["d_remote_machine_name"] = _vrpn_Button.vrpn_Endpoint_IP_d_remote_machine_name_set
    __swig_getmethods__["d_remote_machine_name"] = _vrpn_Button.vrpn_Endpoint_IP_d_remote_machine_name_get
    if _newclass:d_remote_machine_name = _swig_property(_vrpn_Button.vrpn_Endpoint_IP_d_remote_machine_name_get, _vrpn_Button.vrpn_Endpoint_IP_d_remote_machine_name_set)
    __swig_setmethods__["d_remote_port_number"] = _vrpn_Button.vrpn_Endpoint_IP_d_remote_port_number_set
    __swig_getmethods__["d_remote_port_number"] = _vrpn_Button.vrpn_Endpoint_IP_d_remote_port_number_get
    if _newclass:d_remote_port_number = _swig_property(_vrpn_Button.vrpn_Endpoint_IP_d_remote_port_number_get, _vrpn_Button.vrpn_Endpoint_IP_d_remote_port_number_set)
    __swig_setmethods__["d_last_connect_attempt"] = _vrpn_Button.vrpn_Endpoint_IP_d_last_connect_attempt_set
    __swig_getmethods__["d_last_connect_attempt"] = _vrpn_Button.vrpn_Endpoint_IP_d_last_connect_attempt_get
    if _newclass:d_last_connect_attempt = _swig_property(_vrpn_Button.vrpn_Endpoint_IP_d_last_connect_attempt_get, _vrpn_Button.vrpn_Endpoint_IP_d_last_connect_attempt_set)
    __swig_setmethods__["d_tcp_only"] = _vrpn_Button.vrpn_Endpoint_IP_d_tcp_only_set
    __swig_getmethods__["d_tcp_only"] = _vrpn_Button.vrpn_Endpoint_IP_d_tcp_only_get
    if _newclass:d_tcp_only = _swig_property(_vrpn_Button.vrpn_Endpoint_IP_d_tcp_only_get, _vrpn_Button.vrpn_Endpoint_IP_d_tcp_only_set)
vrpn_Endpoint_IP_swigregister = _vrpn_Button.vrpn_Endpoint_IP_swigregister
vrpn_Endpoint_IP_swigregister(vrpn_Endpoint_IP)

class vrpn_Connection(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Connection, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Connection, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Button.delete_vrpn_Connection
    __del__ = lambda self : None;
    def doing_okay(self): return _vrpn_Button.vrpn_Connection_doing_okay(self)
    def connected(self): return _vrpn_Button.vrpn_Connection_connected(self)
    def get_log_names(self, *args): return _vrpn_Button.vrpn_Connection_get_log_names(self, *args)
    def mainloop(self, timeout = None): return _vrpn_Button.vrpn_Connection_mainloop(self, timeout)
    def register_sender(self, *args): return _vrpn_Button.vrpn_Connection_register_sender(self, *args)
    def register_message_type(self, *args): return _vrpn_Button.vrpn_Connection_register_message_type(self, *args)
    def register_handler(self, *args): return _vrpn_Button.vrpn_Connection_register_handler(self, *args)
    def unregister_handler(self, *args): return _vrpn_Button.vrpn_Connection_unregister_handler(self, *args)
    def pack_message(self, *args): return _vrpn_Button.vrpn_Connection_pack_message(self, *args)
    def send_pending_reports(self): return _vrpn_Button.vrpn_Connection_send_pending_reports(self)
    def time_since_connection_open(self, *args): return _vrpn_Button.vrpn_Connection_time_since_connection_open(self, *args)
    def get_time(self): return _vrpn_Button.vrpn_Connection_get_time(self)
    def sender_name(self, *args): return _vrpn_Button.vrpn_Connection_sender_name(self, *args)
    def message_type_name(self, *args): return _vrpn_Button.vrpn_Connection_message_type_name(self, *args)
    def register_log_filter(self, *args): return _vrpn_Button.vrpn_Connection_register_log_filter(self, *args)
    def save_log_so_far(self): return _vrpn_Button.vrpn_Connection_save_log_so_far(self)
    def get_File_Connection(self): return _vrpn_Button.vrpn_Connection_get_File_Connection(self)
    def Jane_stop_this_crazy_thing(self, *args): return _vrpn_Button.vrpn_Connection_Jane_stop_this_crazy_thing(self, *args)
    def get_Jane_value(self): return _vrpn_Button.vrpn_Connection_get_Jane_value(self)
    def addReference(self): return _vrpn_Button.vrpn_Connection_addReference(self)
    def removeReference(self): return _vrpn_Button.vrpn_Connection_removeReference(self)
    def setAutoDeleteStatus(self, *args): return _vrpn_Button.vrpn_Connection_setAutoDeleteStatus(self, *args)
    __swig_setmethods__["d_dispatcher"] = _vrpn_Button.vrpn_Connection_d_dispatcher_set
    __swig_getmethods__["d_dispatcher"] = _vrpn_Button.vrpn_Connection_d_dispatcher_get
    if _newclass:d_dispatcher = _swig_property(_vrpn_Button.vrpn_Connection_d_dispatcher_get, _vrpn_Button.vrpn_Connection_d_dispatcher_set)
vrpn_Connection_swigregister = _vrpn_Button.vrpn_Connection_swigregister
vrpn_Connection_swigregister(vrpn_Connection)

class vrpn_Connection_IP(vrpn_Connection):
    __swig_setmethods__ = {}
    for _s in [vrpn_Connection]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Connection_IP, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Connection]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Connection_IP, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _vrpn_Button.new_vrpn_Connection_IP(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpn_Connection_IP
    __del__ = lambda self : None;
    def connect_to_client(self, *args): return _vrpn_Button.vrpn_Connection_IP_connect_to_client(self, *args)
    def mainloop(self, timeout = None): return _vrpn_Button.vrpn_Connection_IP_mainloop(self, timeout)
vrpn_Connection_IP_swigregister = _vrpn_Button.vrpn_Connection_IP_swigregister
vrpn_Connection_IP_swigregister(vrpn_Connection_IP)

class vrpn_Connection_Loopback(vrpn_Connection):
    __swig_setmethods__ = {}
    for _s in [vrpn_Connection]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Connection_Loopback, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Connection]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Connection_Loopback, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Button.delete_vrpn_Connection_Loopback
    __del__ = lambda self : None;
    def mainloop(self, timeout = None): return _vrpn_Button.vrpn_Connection_Loopback_mainloop(self, timeout)
    def doing_okay(self): return _vrpn_Button.vrpn_Connection_Loopback_doing_okay(self)
    def connected(self): return _vrpn_Button.vrpn_Connection_Loopback_connected(self)
vrpn_Connection_Loopback_swigregister = _vrpn_Button.vrpn_Connection_Loopback_swigregister
vrpn_Connection_Loopback_swigregister(vrpn_Connection_Loopback)


def vrpn_copy_service_name(*args):
  return _vrpn_Button.vrpn_copy_service_name(*args)
vrpn_copy_service_name = _vrpn_Button.vrpn_copy_service_name

def vrpn_copy_service_location(*args):
  return _vrpn_Button.vrpn_copy_service_location(*args)
vrpn_copy_service_location = _vrpn_Button.vrpn_copy_service_location

def vrpn_copy_file_name(*args):
  return _vrpn_Button.vrpn_copy_file_name(*args)
vrpn_copy_file_name = _vrpn_Button.vrpn_copy_file_name

def vrpn_copy_machine_name(*args):
  return _vrpn_Button.vrpn_copy_machine_name(*args)
vrpn_copy_machine_name = _vrpn_Button.vrpn_copy_machine_name

def vrpn_get_port_number(*args):
  return _vrpn_Button.vrpn_get_port_number(*args)
vrpn_get_port_number = _vrpn_Button.vrpn_get_port_number

def vrpn_copy_rsh_program(*args):
  return _vrpn_Button.vrpn_copy_rsh_program(*args)
vrpn_copy_rsh_program = _vrpn_Button.vrpn_copy_rsh_program

def vrpn_copy_rsh_arguments(*args):
  return _vrpn_Button.vrpn_copy_rsh_arguments(*args)
vrpn_copy_rsh_arguments = _vrpn_Button.vrpn_copy_rsh_arguments

def vrpn_set_service_name(*args):
  return _vrpn_Button.vrpn_set_service_name(*args)
vrpn_set_service_name = _vrpn_Button.vrpn_set_service_name

def check_vrpn_cookie(*args):
  return _vrpn_Button.check_vrpn_cookie(*args)
check_vrpn_cookie = _vrpn_Button.check_vrpn_cookie

def check_vrpn_file_cookie(*args):
  return _vrpn_Button.check_vrpn_file_cookie(*args)
check_vrpn_file_cookie = _vrpn_Button.check_vrpn_file_cookie

def vrpn_cookie_size():
  return _vrpn_Button.vrpn_cookie_size()
vrpn_cookie_size = _vrpn_Button.vrpn_cookie_size

def write_vrpn_cookie(*args):
  return _vrpn_Button.write_vrpn_cookie(*args)
write_vrpn_cookie = _vrpn_Button.write_vrpn_cookie

def vrpn_noint_block_write(*args):
  return _vrpn_Button.vrpn_noint_block_write(*args)
vrpn_noint_block_write = _vrpn_Button.vrpn_noint_block_write

def vrpn_noint_block_read(*args):
  return _vrpn_Button.vrpn_noint_block_read(*args)
vrpn_noint_block_read = _vrpn_Button.vrpn_noint_block_read

def vrpn_noint_select(*args):
  return _vrpn_Button.vrpn_noint_select(*args)
vrpn_noint_select = _vrpn_Button.vrpn_noint_select
class vrpn_ConnectionManager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_ConnectionManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_ConnectionManager, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Button.delete_vrpn_ConnectionManager
    __del__ = lambda self : None;
    __swig_getmethods__["instance"] = lambda x: _vrpn_Button.vrpn_ConnectionManager_instance
    if _newclass:instance = staticmethod(_vrpn_Button.vrpn_ConnectionManager_instance)
    def addConnection(self, *args): return _vrpn_Button.vrpn_ConnectionManager_addConnection(self, *args)
    def deleteConnection(self, *args): return _vrpn_Button.vrpn_ConnectionManager_deleteConnection(self, *args)
    def getByName(self, *args): return _vrpn_Button.vrpn_ConnectionManager_getByName(self, *args)
vrpn_ConnectionManager_swigregister = _vrpn_Button.vrpn_ConnectionManager_swigregister
vrpn_ConnectionManager_swigregister(vrpn_ConnectionManager)

def vrpn_get_connection_by_name(*args):
  return _vrpn_Button.vrpn_get_connection_by_name(*args)
vrpn_get_connection_by_name = _vrpn_Button.vrpn_get_connection_by_name

def vrpn_create_server_connection(*args):
  return _vrpn_Button.vrpn_create_server_connection(*args)
vrpn_create_server_connection = _vrpn_Button.vrpn_create_server_connection

def vrpn_ConnectionManager_instance():
  return _vrpn_Button.vrpn_ConnectionManager_instance()
vrpn_ConnectionManager_instance = _vrpn_Button.vrpn_ConnectionManager_instance

class vrpn_Button(vrpn_BaseClass):
    __swig_setmethods__ = {}
    for _s in [vrpn_BaseClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Button, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_BaseClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Button, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vrpn_Button.delete_vrpn_Button
    __del__ = lambda self : None;
    def _print(self): return _vrpn_Button.vrpn_Button__print(self)
    def set_momentary(self, *args): return _vrpn_Button.vrpn_Button_set_momentary(self, *args)
    def set_toggle(self, *args): return _vrpn_Button.vrpn_Button_set_toggle(self, *args)
    def set_all_momentary(self): return _vrpn_Button.vrpn_Button_set_all_momentary(self)
    def set_all_toggle(self, *args): return _vrpn_Button.vrpn_Button_set_all_toggle(self, *args)
vrpn_Button_swigregister = _vrpn_Button.vrpn_Button_swigregister
vrpn_Button_swigregister(vrpn_Button)
vrpn_BUTTON_MAX_BUTTONS = cvar.vrpn_BUTTON_MAX_BUTTONS
VRPN_BUTTON_BUF_SIZE = cvar.VRPN_BUTTON_BUF_SIZE
vrpn_BUTTON_MOMENTARY = cvar.vrpn_BUTTON_MOMENTARY
vrpn_BUTTON_TOGGLE_OFF = cvar.vrpn_BUTTON_TOGGLE_OFF
vrpn_BUTTON_TOGGLE_ON = cvar.vrpn_BUTTON_TOGGLE_ON
vrpn_BUTTON_LIGHT_OFF = cvar.vrpn_BUTTON_LIGHT_OFF
vrpn_BUTTON_LIGHT_ON = cvar.vrpn_BUTTON_LIGHT_ON
vrpn_ALL_ID = cvar.vrpn_ALL_ID

class vrpn_Button_Filter(vrpn_Button):
    __swig_setmethods__ = {}
    for _s in [vrpn_Button]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Button_Filter, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Button]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Button_Filter, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["buttonstate"] = _vrpn_Button.vrpn_Button_Filter_buttonstate_set
    __swig_getmethods__["buttonstate"] = _vrpn_Button.vrpn_Button_Filter_buttonstate_get
    if _newclass:buttonstate = _swig_property(_vrpn_Button.vrpn_Button_Filter_buttonstate_get, _vrpn_Button.vrpn_Button_Filter_buttonstate_set)
    def set_momentary(self, *args): return _vrpn_Button.vrpn_Button_Filter_set_momentary(self, *args)
    def set_toggle(self, *args): return _vrpn_Button.vrpn_Button_Filter_set_toggle(self, *args)
    def set_all_momentary(self): return _vrpn_Button.vrpn_Button_Filter_set_all_momentary(self)
    def set_all_toggle(self, *args): return _vrpn_Button.vrpn_Button_Filter_set_all_toggle(self, *args)
    def set_alerts(self, *args): return _vrpn_Button.vrpn_Button_Filter_set_alerts(self, *args)
    __swig_destroy__ = _vrpn_Button.delete_vrpn_Button_Filter
    __del__ = lambda self : None;
vrpn_Button_Filter_swigregister = _vrpn_Button.vrpn_Button_Filter_swigregister
vrpn_Button_Filter_swigregister(vrpn_Button_Filter)

VRPN_BUTTON_OFF = _vrpn_Button.VRPN_BUTTON_OFF
VRPN_BUTTON_ON = _vrpn_Button.VRPN_BUTTON_ON
class vrpn_BUTTONCB(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_BUTTONCB, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_BUTTONCB, name)
    __repr__ = _swig_repr
    __swig_setmethods__["msg_time"] = _vrpn_Button.vrpn_BUTTONCB_msg_time_set
    __swig_getmethods__["msg_time"] = _vrpn_Button.vrpn_BUTTONCB_msg_time_get
    if _newclass:msg_time = _swig_property(_vrpn_Button.vrpn_BUTTONCB_msg_time_get, _vrpn_Button.vrpn_BUTTONCB_msg_time_set)
    __swig_setmethods__["button"] = _vrpn_Button.vrpn_BUTTONCB_button_set
    __swig_getmethods__["button"] = _vrpn_Button.vrpn_BUTTONCB_button_get
    if _newclass:button = _swig_property(_vrpn_Button.vrpn_BUTTONCB_button_get, _vrpn_Button.vrpn_BUTTONCB_button_set)
    __swig_setmethods__["state"] = _vrpn_Button.vrpn_BUTTONCB_state_set
    __swig_getmethods__["state"] = _vrpn_Button.vrpn_BUTTONCB_state_get
    if _newclass:state = _swig_property(_vrpn_Button.vrpn_BUTTONCB_state_get, _vrpn_Button.vrpn_BUTTONCB_state_set)
    def __init__(self): 
        this = _vrpn_Button.new_vrpn_BUTTONCB()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpn_BUTTONCB
    __del__ = lambda self : None;
vrpn_BUTTONCB_swigregister = _vrpn_Button.vrpn_BUTTONCB_swigregister
vrpn_BUTTONCB_swigregister(vrpn_BUTTONCB)

class vrpn_BUTTONSTATESCB(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_BUTTONSTATESCB, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_BUTTONSTATESCB, name)
    __repr__ = _swig_repr
    __swig_setmethods__["msg_time"] = _vrpn_Button.vrpn_BUTTONSTATESCB_msg_time_set
    __swig_getmethods__["msg_time"] = _vrpn_Button.vrpn_BUTTONSTATESCB_msg_time_get
    if _newclass:msg_time = _swig_property(_vrpn_Button.vrpn_BUTTONSTATESCB_msg_time_get, _vrpn_Button.vrpn_BUTTONSTATESCB_msg_time_set)
    __swig_setmethods__["num_buttons"] = _vrpn_Button.vrpn_BUTTONSTATESCB_num_buttons_set
    __swig_getmethods__["num_buttons"] = _vrpn_Button.vrpn_BUTTONSTATESCB_num_buttons_get
    if _newclass:num_buttons = _swig_property(_vrpn_Button.vrpn_BUTTONSTATESCB_num_buttons_get, _vrpn_Button.vrpn_BUTTONSTATESCB_num_buttons_set)
    __swig_setmethods__["states"] = _vrpn_Button.vrpn_BUTTONSTATESCB_states_set
    __swig_getmethods__["states"] = _vrpn_Button.vrpn_BUTTONSTATESCB_states_get
    if _newclass:states = _swig_property(_vrpn_Button.vrpn_BUTTONSTATESCB_states_get, _vrpn_Button.vrpn_BUTTONSTATESCB_states_set)
    def __init__(self): 
        this = _vrpn_Button.new_vrpn_BUTTONSTATESCB()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpn_BUTTONSTATESCB
    __del__ = lambda self : None;
vrpn_BUTTONSTATESCB_swigregister = _vrpn_Button.vrpn_BUTTONSTATESCB_swigregister
vrpn_BUTTONSTATESCB_swigregister(vrpn_BUTTONSTATESCB)

class vrpn_Button_Remote(vrpn_Button):
    __swig_setmethods__ = {}
    for _s in [vrpn_Button]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, vrpn_Button_Remote, name, value)
    __swig_getmethods__ = {}
    for _s in [vrpn_Button]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, vrpn_Button_Remote, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _vrpn_Button.new_vrpn_Button_Remote(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _vrpn_Button.delete_vrpn_Button_Remote
    __del__ = lambda self : None;
    def mainloop(self): return _vrpn_Button.vrpn_Button_Remote_mainloop(self)
    def register_change_handler(self, *args): return _vrpn_Button.vrpn_Button_Remote_register_change_handler(self, *args)
    def unregister_change_handler(self, *args): return _vrpn_Button.vrpn_Button_Remote_unregister_change_handler(self, *args)
    def register_states_handler(self, *args): return _vrpn_Button.vrpn_Button_Remote_register_states_handler(self, *args)
    def unregister_states_handler(self, *args): return _vrpn_Button.vrpn_Button_Remote_unregister_states_handler(self, *args)
vrpn_Button_Remote_swigregister = _vrpn_Button.vrpn_Button_Remote_swigregister
vrpn_Button_Remote_swigregister(vrpn_Button_Remote)


def register_button_change_handler(*args):
  return _vrpn_Button.register_button_change_handler(*args)
register_button_change_handler = _vrpn_Button.register_button_change_handler

def get_button_change_handler():
  return _vrpn_Button.get_button_change_handler()
get_button_change_handler = _vrpn_Button.get_button_change_handler


